name: Codzienna Aktualizacja Strony
on:
  schedule:
    - cron:  '0 6 * * *' # 8:00 rano codziennie
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install requests beautifulsoup4
      - run: python agent_page.py
      - uses: actions/upload-pages-artifact@v3
        with: { path: . }
deploy:
  # Potrzebuje zadania 'build-and-deploy', aby się zakończyło
  needs: build-and-deploy

  # --- POPRAWKA TUTAJ: Dodaj wcięcie (2 spacje) przed 'permissions' ---
  permissions:
    pages: write
    id-token: write

  # Określ środowisko
  environment:
    name: github-pages
    url: ${{ steps.deployment.outputs.page_url }}
  # Uruchom na maszynie ubuntu
  runs-on: ubuntu-latest
  steps:
    # Publikuj artefakt na stronie
    - name: Publikacja na GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
