# Nazwa naszego zadania
name: Codzienna Aktualizacja Strony z Raportami

# Kiedy zadanie ma się uruchamiać
on:
  schedule:
    # Codziennie o 7:00 UTC (9:00 rano czasu polskiego letniego)
    - cron:  '0 7 * * *'
  # Pozwala na ręczne uruchomienie
  workflow_dispatch:

# Definicja zadań
jobs:
  # Zadanie 1: Budowanie strony
  build:
    runs-on: ubuntu-latest
    steps:
      # Krok 1.1: Pobranie kodu repozytorium
      - name: Pobieranie kodu
        uses: actions/checkout@v4

      # Krok 1.2: Ustawienie środowiska Python
      - name: Ustawienie Pythona
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Krok 1.3: Instalacja potrzebnych bibliotek
      - name: Instalacja bibliotek
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
      
      # Krok 1.4: Uruchomienie naszego skryptu Python, który tworzy index.html
      - name: Uruchomienie skryptu agent_page.py
        run: python agent_page.py
      
      # Krok 1.5: Przygotowanie wygenerowanej strony do publikacji
      - name: Przygotowanie artefaktu strony
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  # Zadanie 2: Publikacja strony
  deploy:
    needs: build # To zadanie musi poczekać, aż zadanie 'build' się zakończy
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # Krok 2.1: Publikacja przygotowanej strony
      - name: Publikacja na GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
